import React from "react";
import { Link } from "react-router-dom";

function Home() {
    return (
        <div>
            <img src={"https://res.cloudinary.com/djs2shvhl/image/upload/v1751635738/00056-664118011_lom7tx.png"} alt="generated by IA" style={{width: '100%', height: '500px', objectFit: 'cover', objectPosition: 'bottom', overflow: 'hidden'}}></img>
            <div className="container d-flex flex-column align-items-center">
                <h1 className="my-5">Bienvenue sur Knowledge Learning</h1>
                <Link to="/formations" className="btn btn-primary" style={{width:'30%'}}>Nos formations</Link>
            </div>
        </div>
    )
}

export default Home;